apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      jsonPointers:
        - /data/metastore-site.xml
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/template/spec/containers/env[] | select(.name == "MYSQL_USER")
  destination:
    namespace: test-1995
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.spec.repo }}
    path: test-1995-deploy/src/main/resources/apps/spark-infrastructure
    targetRevision: {{ .Values.spec.targetRevision }}
    {{ if .Values.spec.helm.valueFiles }}
    helm:
      valueFiles:
        {{- range .Values.spec.helm.valueFiles }}
        - {{ . }}
        {{- end }}    
    {{ end }}
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true # https://github.com/argoproj/argo-cd/issues/820#issuecomment-135463693
    {{- if .Values.spec.syncPolicy }}
      {{- with .Values.spec.syncPolicy.syncOptions }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- end }}